### ISSUE TITLE
#before_all and #after_all do not behave as expected

### ISSUE THREAD

**Issue by kevinrood** [jeremyevans/minitest-hooks#11]
First off, thank you for your gem :smile: 

Based on the readme, I would expect the `#before_all` and `#after_all` methods in a base test class to be called once each for the test suite. However, they are getting called once per test class. Is this a bug, or by design?

**Comment by jeremyevans** [comment]
Once per test class/suite is expected and by design, with subclasses being considering separate classes/suites.  Minitest does not offer the facility to run specs for all subclasses of a class when the class's specs are run.  Minitest treats all test classes/suites as independent from a scheduling perspective.

**Comment by kevinrood** [comment]
@jeremyevans good to know, thank you.

I was able to accomplish what I needed in part using:

```ruby
Minitest.after_run do
  # code to run after all tests
end
```
