### ISSUE TITLE
Before each doesn't work with Minitest::Test

### ISSUE THREAD

**Issue by bmorton** [jeremyevans/minitest-hooks#18]
I've been looking at replacing some bespoke before/after implementation that we've got in our app and I started hooking this library up to play with it a bit.  I noticed that the [passthrough `before(:each)` feature](https://github.com/jeremyevans/minitest-hooks/blob/9ea89c8a27ff698f39cc303d2f3e45fe8742b0ba/lib/minitest/hooks/test.rb#L118) doesn't seem to work.  I get this error:

```
minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:118:in `before': super: no superclass method `before' for TestMeme:Class (NoMethodError)
```

I've got a standalone repro here: https://github.com/bmorton/minitest-hooks-repro

Would you accept a PR that adds the missing methods in `lib/minitest/hooks/test.rb`?

**Comment by jeremyevans** [comment]
If you are using `Minitest::Test` instead of `Minitest::Spec`, then you can't use `before(:each)` and `after(:each)`, you need to use `def setup` and `def teardown`.  This is expected and by design. If you want `before(:each)` and `after(:each)` to work in `Minitest::Test`, you'll need to convince upstream minitest to move the methods from `Minitest::Spec` to `Minitest::Test`.

**Comment by bmorton** [comment]
I see.  Is it worth removing the call to super in `lib/minitest/hooks/test.rb` then?  Or is that code reused with `Minitest::Spec`?  It's a simple fix in my test suite and I can fix it without changing the library, just thought I'd offer to contribute back since I got stuck here for a while trying to figure out what was up.

**Comment by jeremyevans** [comment]
The code is shared with `Minitest::Spec`.  Removing the `super` call would break `before(:each)` and `after(:each)` in `Minitest::Spec` I think.  It also wouldn't do what you want in `Minitest::Test`, because dropping the `super` call would make it silently not define any method.  To do what you want would require recreating `Minitest::Spec` behavior inside minitest-hooks, which I don't think is appropriate.  That's why I think you should work with upstream minitest if you think `Minitest::Test` should support `before(:each)`.

**Comment by bmorton** [comment]
Alrighty, thanks for the advice!  I'll probably just create a new tiny gem that combines the things that I need.  I suspect that upstream `Minitest` will not be open to a change like this.
