### ISSUE TITLE
`before :all` / `after :all` / `around :all` are called for empty classes but should not

### ISSUE THREAD

**Issue by grosser** [jeremyevans/minitest-hooks#7]
@jeremyevans not sure if you got a solution, just leaving this here in case someone does :)

**Comment by jeremyevans** [comment]
@grosser Is this really a problem?  How often are empty classes used? What's the downside, other than a slight performance decrease for unnecessary hook calls?

If you did want to fix this, this should be fixed at the Minitest level, by having it ignore classes that don't have any specs. You can do that by redefining `Minitest::Runnable.runnables`.  I don't think it's something that should be handled in minitest-hooks, you should submit a pull request to minitest itself if you want that behavior changed.

**Comment by grosser** [comment]
A bunch of times:

describe xxx do <- empty class
  describe yyy do
    its ...
  end
end

This is not a minitest problem since it does not run anything if the class
is empty, just minitest-hooks does. I know it's not an urgent issue, but
it's unexpected and degrades performance, so I'd prefer to keep this open.

**Comment by jeremyevans** [comment]
Minitest doesn't currently offer the necessary integration point for minitest-hooks to determine whether the runnable will execute specs or not.  It would require changes `Minitest::Runnable.run` to support this.  Either split the method into two methods, one that does the filtering of methods, and one that iterates over the filtered methods, or have it return before calling `with_info_handler` if there weren't any filtered methods.

I'll send a pull request to minitest to do the latter, since it seems less invasive.  If it gets accepted, I'll reopen this and make changes to support it.  But if it gets rejected, then I won't be supporting this in minitest-hooks.  Empty spec classes as given in your example are a code smell anyway, IMO. :)

**Comment by grosser** [comment]
thx!

this does not look smelly to me, putting all the it's directly into the
first describe would be more confusing imo.

describe User do
  describe "#is_admin?" do
    it "is admin when role is admin" do
      ...
    end
  end
  ... 10 more of these blocks ...
end

**Comment by jeremyevans** [comment]
I would say for things like that, you shouldn't use the nested spec class (`describe "#is_admin?"`).  Nested spec classes should be used only if they are necessary, such as when you are defining methods other than tests inside the class.  Subclassing without changing behavior is wasteful.  If you follow that design principle, I think you'll find that empty spec classes are uncommon.

**Comment by grosser** [comment]
So you are suggesting to just put everything into the same namespace ?
That sounds like a great way to completely lose context :)
I think of nested describes like modules or methods, there is some
overhead, but that's made up by increasing clarity.

For example first 3 google results for "rspec example":

uses nesting http://blog.teamtreehouse.com/an-introduction-to-rspec
uses nesting http://rspec.info/
uses nesting
http://code.tutsplus.com/tutorials/ruby-for-newbies-testing-with-rspec--net-21297

**Comment by jeremyevans** [comment]
I'm saying only use a context if you need a context.  If the two contexts are exactly the same, it's better to have a single context instead of multiple contexts.  It's also better for randomness if a single context is used, as if you use multiple contexts, it will not interleave the specs for them.

I realize this unnecessary context thing is encouraged by rspec. I disagree with that approach.

Anyway, this isn't a forum for philosophical debate on better approaches to testing.  I've put in a pull request to minitest, we'll see what happens from there.

**Comment by jeremyevans** [comment]
Minitest merged my pull request, so after minitest makes another release, I'll add a patch to minitest-hooks to depend on that version and skip running hooks for empty classes.

**Comment by grosser** [comment]
great, thx!
